version: '3.7'

services:
  holy-jenkins:
    image: jenkins/jenkins:lts
    container_name: holy-jenkins
    ports:
      - "18081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Docker 소켓 마운트
      - /var/home/jenkins_ssh:/var/jenkins_home/.ssh  # SSH 디렉토리 마운트
    networks:
      - holy-jenkins-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8008:80"
    depends_on:
      - holy-jenkins
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - holy-jenkins-network

networks:
  holy-jenkins-network:
    name: holy-jenkins-network
    driver: bridge

volumes:
  jenkins_home:
