services:
  app: # steach-server 애플리케이션 서비스 정의
    image: steach-server:latest # 사용할 Docker 이미지 지정
    container_name: steach-server # 컨테이너 이름 지정
    environment:
      - SPRING_PROFILES_ACTIVE=prod # Spring Boot 프로파일 설정
    ports:
      - "18080:18080" # 호스트의 18080 포트를 컨테이너의 18080 포트에 매핑

  nginx: # Nginx 서비스 정의
    image: nginx:latest # 사용할 Nginx 이미지 지정
    container_name: steach-server-nginx # 컨테이너 이름 지정
    ports:
      - "18008:80" # 호스트의 80 포트를 컨테이너의 18008 포트에 매핑
    depends_on:
      - app # Nginx가 steach-server 애플리케이션에 의존
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # 호스트의 Nginx 설정 파일을 컨테이너로 마운트
      # 다음과 같이 보여야 합니다: 끝에 있는 것은 읽기 전용으로 만드는데, 이는 구성 파일에 대한 좋은 습관입니다.
