auth_enabled: false # 인증을 비활성화합니다.

server:
  http_listen_port: 3100 # Loki 서버가 HTTP 요청을 수신하는 포트를 설정합니다.

ingester:
  lifecycler:
    address: 127.0.0.1 # Loki의 Lifecycler 주소를 설정합니다.
    ring:
      kvstore:
        store: inmemory # 인메모리 키-값 저장소를 사용합니다.
    final_sleep: 0s # 최종 슬립 시간 설정
  chunk_idle_period: 5m # 청크가 유휴 상태일 때 유지되는 시간
  chunk_retain_period: 30s # 청크가 유지되는 시간
  max_transfer_retries: 0 # 전송 재시도 최대 횟수

schema_config:
  configs:
    - from: 2020-10-24 # 이 날짜부터 적용되는 설정
      store: boltdb-shipper # 볼트DB 저장소 사용
      object_store: filesystem # 파일 시스템을 객체 저장소로 사용
      schema: v11 # 스키마 버전
      index:
        prefix: index_ # 인덱스 접두사
        period: 168h # 인덱스 기간

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index # 활성 인덱스 디렉토리
    cache_location: /loki/boltdb-cache # 캐시 위치
    shared_store: filesystem # 공유 저장소로 파일 시스템 사용
  filesystem:
    directory: /loki/chunks # 청크 저장소 디렉토리

limits_config:
  enforce_metric_name: false # 메트릭 이름 강제 적용 여부
  reject_old_samples: true # 오래된 샘플을 거부할지 여부
  reject_old_samples_max_age: 168h # 오래된 샘플의 최대 허용 연령

chunk_store_config:
  max_look_back_period: 0s # 청크의 최대 조회 기간

table_manager:
  retention_deletes_enabled: false # 보존 삭제 활성화 여부
  retention_period: 0s # 보존 기간



#  Loki는 로그 수집 및 저장을 담당하는 도구입니다. 이 파일에서는 Loki 서버의 포트 설정, 로그 청크의 유지 기간, 인덱스 설정, 저장소 설정 등을 정의합니다.
#  auth_enabled를 false로 설정하여 인증을 비활성화하고, server 섹션에서 Loki가 HTTP 요청을 수신할 포트를 지정합니다.
#  ingester 섹션에서는 로그 청크의 유휴 기간과 유지 기간을 설정하며, schema_config와 storage_config 섹션에서는 인덱스와 저장소에 대한 구성을 정의합니다.
#  limits_config 섹션에서는 로그 샘플의 최대 허용 연령을 설정하고, chunk_store_config과 table_manager 섹션에서는 청크 저장소와 테이블 관리 설정을 정의합니다.
